config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations",
    passwords: "users/passwords"}
  root to: 'goals#index'
  resources :goals, shallow: true do
    resources :action_records
    resources :goal_actions
    get 'user', on: :collection
  end
  resources :users
end

app/models/action_record.rb
class ActionRecord < ApplicationRecord
    belongs_to :user
    belongs_to :goal
    belongs_to :goal_action

    mount_uploader :action_image, IconUploader
end

app/controllers/action_records_controller.rb
class ActionRecordsController < ApplicationController
    before_action :authenticate_user!, only:[:new, :edit, :destroy]
    before_action :correct_user, only: [:edit, :update]

    def index
        @goal = Goal.find(params[:goal_id])
        @action_records = @goal.action_records.order(id: "DESC")
    end

    def new
        @action_record = ActionRecord.new
        @goal = Goal.find(params[:goal_id])
        @goal_actions = @goal.goal_actions
        @user = @goal.user
        redirect_to(root_path) unless current_user?(@user)
    end

    def create
        @action_record = ActionRecord.new(action_record_params)
        @action_record.user_id = current_user.id
        @action_record.goal_id = params[:goal_id]
        @goal = Goal.find(params[:goal_id])
        if @action_record.save
            redirect_to goal_action_records_path(@goal)
            flash[:success] = "保存しました"
        else
            redirect_back(fallback_location: root_path)
        end
        update_goal_rank
    end

    def edit
        @action_record = ActionRecord.find(params[:id])
        @goal = @action_record.goal
        @goal_actions = current_user.goal_actions
    end

    def update
        @action_record = ActionRecord.find(params[:id])
        @goal = @action_record.goal
        @action_record.assign_attributes action_record_params
        if @action_record.save && @action_record.user_id == current_user.id
            redirect_to goal_action_records_path(@goal) 
            flash[:success] = "保存しました"
        else
            redirect_back(fallback_location: root_path)
        end
        update_goal_rank
    end

    def destroy
        @action_record = ActionRecord.find(params[:id])
        @goal = @action_record.goal
        if @action_record.user_id == current_user.id
            @action_record.destroy
            update_goal_rank
            redirect_to goal_action_records_path(@goal)
            flash[:warning] = "削除しました"
        end
    end

    def update_goal_rank
        @action_records = @goal.action_records.all
        case @action_records.count
        when 1
            @goal.update(rank:1)
            flash[:info] = "達成ランクが1になりました"
        when 2
            @goal.update(rank:2)
            flash[:info] = "達成ランクが2になりました"
        when 3
            @goal.update(rank:3)
            flash[:info] = "達成ランクが3になりました"
        when 5
            @goal.update(rank:4)
            flash[:info] = "達成ランクが4になりました"
        when 8
            @goal.update(rank:5)
            flash[:info] = "達成ランクが5になりました"
        when 13
            @goal.update(rank:6)
            flash[:info] = "達成ランクが6になりました"
        when 21
            @goal.update(rank:7)
            flash[:info] = "達成ランクが7になりました"
        when 34
            @goal.update(rank:8)
            flash[:info] = "達成ランクが8になりました"
        when 55
            @goal.update(rank:9)
            flash[:info] = "達成ランクが9になりました"
        when 89
            @goal.update(rank:10)
            flash[:info] = "達成ランクが10になりました!目標達成です◎"
        else
            nil
        end
    end

    private
    def action_record_params
        params.require(:action_record).permit(
            :action_image, :action_comment, :goal_action_id
        )
    end

    def correct_user
        @user = ActionRecord.find(params[:id]).user
        redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/action_records_helper.rb
module ActionRecordsHelper
end

app/views/action_records/_form.html.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h1 積み上げ記録追加
            - if @action_record.errors.present?
                ul#error_explanation
                    - @action_record.errors.full_messages.each do |message|
                        li = message
            = form_for [@goal, @action_record] do |f|
                .form-group
                    = f.label :行動を選択
                    = f.collection_select(:goal_action_id, @goal_actions, :id, :action_name, {prompt: false}, {class: "form-control"})
                .form-group
                    = f.label :画像を追加
                    = f.file_field :action_image, class: 'form-control-file'
                .form-group
                    = f.label :コメントを入力
                    = f.text_field :action_comment, class: 'form-control', placeholder: "今日はいつもより5回多くスクワットできた。"
                = f.submit "登録", class:"btn btn-primary btn-block"
                = link_to "戻る", :back,class: 'btn btn-light btn-block my-3'

app/views/action_records/edit.html.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h1 積み上げ記録追加
            - if @action_record.errors.present?
                ul#error_explanation
                    - @action_record.errors.full_messages.each do |message|
                        li = message

            = form_with model: @action_record, local: true do |f|
                .form-group
                    = f.label :行動を選択
                    = f.collection_select(:goal_action_id, @goal_actions, :id, :action_name, {prompt: false}, {class: "form-control"})
                .form-group
                    = f.label :画像を追加
                    = f.file_field :action_image, class: 'form-control-file'
                .form-group
                    = f.label :コメントを入力
                    = f.text_field :action_comment, class: 'form-control'
                = f.submit "登録", class:"btn btn-primary btn-block"
                = link_to "戻る", :back,class: 'btn btn-light btn-block my-3'

app/views/action_records/index.html.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h1 #{@goal.goal_content}の積み上げ記録
            - @action_records.each do |action_record|
                .card.bg-light.my-3
                    .row
                        .col-sm-2
                            - if action_record.action_image_url.present?
                                = image_tag action_record.action_image_url, class:'m-3', width: '80px'
                            - else
                                = image_tag 'hata.svg', class:' m-3', width: '100px'
                        .col-sm-10 
                            .card-body
                                h5.card-title
                                    = action_record.goal_action.action_name
                                p.card-text
                                    = action_record.action_comment
                                p.card-text
                                    = action_record.updated_at.strftime("%Y年%m月%d日 %H時%M分")
                                    - if @goal.user_id == current_user&.id
                                        = link_to "https://twitter.com/share?url=#{ request.url }&text=#{ action_record.goal.goal_content }の行動を記録しました&hashtags=今日の積み上げ", class: 'btn btn-default' do
                                            i.fa.fa-twitter style='color: #3399FF;'
                                            |  Twitterでシェア
                                p.card-text.text-right
                                    - if @goal.user_id == current_user&.id
                                        = link_to_if @goal.user_id == current_user.id, '編集', edit_action_record_path(action_record), class: 'btn btn-primary mr-3 text-right'
                                        = link_to_if @goal.user_id == current_user.id,'削除', action_record_path(action_record), method: :delete, remote: true,class: 'btn btn-primary mr-3'
            = link_to '目標詳細に戻る', goal_path(@goal), class: 'btn btn-light mr-3'
            - if @goal.user_id == current_user&.id
                = link_to '積み上げ記録を追加', new_goal_action_record_path(@goal),
                    class: 'btn btn-light m-3'
        .col-md-1

app/views/action_records/new.slim
= render partial: 'form'