config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations",
    passwords: "users/passwords"}
  root to: 'goals#index'
  resources :goals, shallow: true do
    resources :action_records
    resources :goal_actions
    get 'user', on: :collection
  end
  resources :users
end

app/models/goal.rb
class Goal < ApplicationRecord
    validates :goal_content, presence: true
    validates :identity_content, presence: true
    validates :rank, presence: true

    belongs_to :user
    belongs_to :goal_category

    has_many :goal_actions, dependent: :destroy
    has_many :action_records, dependent: :destroy

    accepts_nested_attributes_for :goal_actions
end

app/models/goal_action.rb
class GoalAction < ApplicationRecord
    validates :action_name, presence: true

    belongs_to :user, optional: true
    belongs_to :goal, optional: true

    has_many :action_records, dependent: :destroy
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :authenticate_user!, only:[:new, :edit, :destroy, :user]
    before_action :correct_user, only: [:edit, :update]
    
    def index
        @goal_categories = GoalCategory.all
        if params[:search].present?
            @goals = Goal.where('goal_content LIKE ?', "%#{params[:search]}%").order(rank: "DESC")
        elsif params[:goal_category_id].present?
            @goal_category = GoalCategory.find(params[:goal_category_id])
            @goals = @goal_category.goals.order(rank: "DESC")
        else
            #rank順に並べる
            @goals = Goal.order(rank: "DESC")
        end
    end

    def new
        @goal = Goal.new
        @goal.goal_actions.build
    end

    def create
        @goal = current_user.goals.create(goal_params)
        if @goal.save
            redirect_to action: :index
            flash[:success] = "保存しました"
        else
            render :new
        end
    end

    def edit
        @goal = Goal.find(params[:id])
        @goal_categories = GoalCategory.all
    end

    def show
        @goal = Goal.find(params[:id])
        @goal_actions = @goal.goal_actions
        @action_record = ActionRecord.new
    end

    def update
        @goal = Goal.find(params[:id])
        @goal.assign_attributes goal_params
        if @goal.save && @goal.user_id == current_user.id
            redirect_to action: :index
            flash[:success] = "保存しました"
        else
            render :edit
        end
    end

    def destroy
        @goal = Goal.find(params[:id])
        if @goal.user_id == current_user.id
            @goal.destroy
            redirect_to goals_url
            flash[:warning] = "目標を削除しました"
        end
    end

    def user
        #目標が最新のもの順に並べる
        @goals = Goal.where(user_id: current_user.id).order(id: "DESC")
    end

    private
    def goal_params
        params.require(:goal).permit(
            :goal_content,:identity_content,:rank,:goal_category_id,
            goal_actions_attributes: [:id, :action_name, :user_id]
        )
    end

    def correct_user
        @user = Goal.find(params[:id]).user
        redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.slim
- if @goal.errors.present?
    ul#error_explanation
        - @goal.errors.full_messages.each do |message|
            li = message

= form_with model: @goal, local: true do |f|
    .form-group
        = f.label :goal_content
        = f.text_field :goal_content, class: 'form-control', placeholder: "2月までに3kg痩せる"
        small.form-text.text-muted 抽象的な目標ではなく、数値などを入れた具体的な目標にすることで、達成率を上げることができます。
    .form-group
        = f.fields_for :goal_actions do |af|
            = af.hidden_field :user_id, value: current_user.id
            = af.label :行動
            small.text-muted  ※後で違う行動も追加できます!
            = af.text_field :action_name, class: 'form-control', placeholder: "朝起きたら、HIITを4分やる"
            small.form-text.text-muted 
                | 毎日できるような、ハードルが低い行動にすると、続けやすいためおすすめです。
                br
                | やる時間なども決めると、行動ができる確率をあげることができます。
    .form-group
        = f.label :identity_content
        = f.text_field :identity_content, class: 'form-control', placeholder: "健康的でいたい"
        small.form-text.text-muted 
            | その目標を達成したいと思った自分の価値観を書いてください。
            br
            | これを書くことで、その目標が人から言われたことではなく、自分の意志で本当に達成したいと思った目標なのか確認できます。
    .form-group
        = f.label :カテゴリー
        = f.collection_select(:goal_category_id, GoalCategory.all, :id, :name, {prompt: false}, {class: "form-control"})
    .text-center
        = f.submit "登録", class:"btn btn-primary btn-block"
        = link_to "戻る", :back,class: 'btn btn-light btn-block my-3'

app/views/goals/_goal.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            - if current_user.present? && current_user.goals.blank?
                .card.bg-light.mb-3
                    .card-body 
                        .card-title 
                            h5 目標を登録してみよう!
                        .card-text
                            = link_to '登録する', new_goal_path, class:'btn btn-primary mt-3'
            - if current_user.blank?
                .card.bg-light.mb-3
                    .card-body 
                        .card-title 
                            h5 ログインして目標を登録してみよう!
                        .card-text
                            = link_to 'ログイン', new_user_session_path, class:'btn btn-primary mt-3'
            - @goals.each do |goal|
                .card.bg-light.my-3
                    .card-body
                        .row
                            .col-5.col-md-2
                                .card-text
                                    - if goal.user.icon.url.present?
                                        = image_tag goal.user.icon.url, class:'image', width: '60px'
                                    - else 
                                        = image_tag 'azarasi.svg', class:'image', width: '60px'
                                    br
                                    p = link_to "#{goal.user.display_name}", user_path(goal.user.id), class: 'my-1'
                            .col-7.col-md-8
                                h5.card-title
                                    br
                                    = goal.goal_content
                        p.card-text
                            i.fa.fa-star
                            = "達成Lv.#{goal.rank}"
                            .progress 
                                .progress-bar.progress-bar-striped aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" style="width: #{goal.rank * 10}%"
                        h6.card-text
                            = link_to "#{goal.goal_category.name}", goals_path(goal_category_id:goal.goal_category.id),
                                class: 'btn btn-outline-primary btn-sm mr-1'
                            - if goal.user == current_user && goal.action_records.blank?
                                .balloon1
                                    p 積み上げ記録をつけてみよう
                        hr
                        h6.card-text
                            = link_to '詳細', goal_path(goal), class: 'card-link mr-3'
                            - if goal.user_id == current_user&.id
                                = link_to_if goal.user_id == current_user.id, '積み上げ記録を追加', new_goal_action_record_path(goal),
                                    class: 'card-link mr-3'
        .col-md-1

app/views/goals/edit.slim
= render partial: 'form'

app/views/goals/index.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h1 みんなの目標
            ul.navbar-nav
                li.nav-item.dropdown
                    a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                        i.fa.fa-folder-open カテゴリ
                    .dropdown-menu aria-labelledby="navbarDropdown"
                        = link_to "すべて", goals_path, class: 'dropdown-item'
                        - @goal_categories.each do |gc|
                            = link_to "#{gc.name}", goals_path(goal_category_id:gc.id), class: 'dropdown-item'
                = form_tag(goals_path,:method => 'get', class:'form-inline') do 
                    = text_field_tag :search, nil, {class: 'form-control mr-sm-2', placeholder: "目標を入力"}
                    = submit_tag '検索', :name => nil, class: 'btn btn-outline-success my-2 my-sm-0'
                .col-md-1
= render partial: 'goal'

app/views/goals/new.slim
= render partial: 'form'

app/views/goals/show.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h1 #{@goal.goal_content}の目標詳細
            p.text-right
                = link_to "by#{@goal.user.display_name}", user_path(@goal.user)
            table.table.table-borderless.table-striped
                thead
                    tr
                        th 
                        th
                    tbody
                            tr
                                th scope="row" 目標
                                td = @goal.goal_content
                            - @goal_actions.each.with_index(1) do |goal_action, index|
                                tr
                                    th scope="row" 行動#{index}
                                    td = goal_action.action_name
                            tr
                                th scope="row" 価値観
                                td = @goal.identity_content
                            tr
                                th scope="row" カテゴリ
                                td = @goal.goal_category.name
            - if @goal.user_id == current_user&.id
                .text-right
                    = link_to_if @goal.user_id == current_user.id, '編集', edit_goal_path(@goal), class: 'btn btn-primary mr-3 text-right'
                    = link_to_if @goal.user_id == current_user.id,'削除', goal_path(@goal), method: :delete, remote: true,class: 'btn btn-primary mr-3'
            br
            = link_to '行動一覧', goal_goal_actions_path(@goal), class: 'btn btn-light mr-3'
            = link_to '積み上げ記録一覧', goal_action_records_path(@goal), class: 'btn btn-light mr-3'
        .col-md-1

app/views/goals/user.slim
.container
    .row
        .col-md-1
        .col-md-10.col-sm-12
            h1 積み上げ記録を追加
        .col-md-1
= render partial: 'goal'